# Generated by Django 2.0.4 on 2018-04-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='images/None/No0img.jpg', upload_to='images/'),
        ),
    ]
